# Use the ollama base image
FROM ollama/ollama:latest 

EXPOSE 11434

# Start the server (replace with the appropriate command to start the server if needed)
CMD ["sh", "-c", "ollama pull llama3 && ollama serve"]